#!/usr/bin/env bash
i=1
while [ $i -le 100 ]
do
	if [ $((i % 3)) -eq 0 ]
	then
		if [ $((i % 5)) -eq 0 ]
		then
			echo FizzBuzz
		else
			echo Fizz
		fi
	elif [ $((i % 5)) -eq 0 ]
	then
		echo Buzz
	else
		echo $i
	fi
	((i++))
done

