#!/usr/bin/env bash
# Check a file
sfile="school"

if [ -e $sfile ]
then
	echo school file exists
	if [ -s $sfile ]
	then
		echo school file is not empty
	else
		echo school file is empty
	fi

	if [ -f $sfile ]
	then
		echo school is a regular file
	fi
else
	echo school file does not exist
fi
