#!/usr/bin/env bash
# Script to change loopback ip
sudo cp /etc/hosts new_hosts
sudo chmod 666 new_hosts
echo "127.0.0.2	localhost" > new_hosts
echo "8.8.8.8	facebook.com" >> new_hosts
sudo cp -f new_hosts /etc/hosts
